CREATE TABLE IF NOT EXISTS joueurs
(
    id    INTEGER NOT NULL AUTO_INCREMENT,
    name   VARCHAR(128) NOT NULL,
    email   VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS games
(
    id    INTEGER NOT NULL AUTO_INCREMENT,
    mode   INTEGER NOT NULL,
    name   VARCHAR(128) NOT NULL,
    currentplayerid   INTEGER NOT NULL,
    status  TINYINT NOT NULL,
    PRIMARY KEY (id)
);