CREATE TABLE IF NOT EXISTS PLAYERS
(
    id    INTEGER NOT NULL AUTO_INCREMENT,
    name   VARCHAR(128) NOT NULL,
    email   VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS GAMES
(
    id    INTEGER NOT NULL AUTO_INCREMENT,
    mode   INTEGER NOT NULL,
    name   VARCHAR(128) NOT NULL,
    currentplayerid   INTEGER NOT NULL,
    status  TINYINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS GAMEPLAYER
(
    id    INTEGER NOT NULL AUTO_INCREMENT,
    playerId  INTEGER NOT NULL,
    gameId  INTEGER NOT NULL,
    remainingShots   INTEGER NOT NULL,
    score   INTEGER NOT NULL,
    `order`   INTEGER NOT NULL,
    `rank`   INTEGER NOT NULL ,

    PRIMARY KEY (id),
    CONSTRAINT FK_JoueursId FOREIGN KEY (playerId) REFERENCES PLAYERS(id),
    CONSTRAINT FK_GamesId FOREIGN KEY (gameId) REFERENCES GAMES(id)
);